### Posts API
//to be done

### Comments API

### Create comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "<post-id>",
  "author": "Example Author",
  "content": "This is a new comment."
}

### Get comments by postId
GET http://localhost:3000/comments?postId=<post-id>

### Get comment by id
GET http://localhost:3000/comments/<comment-id>

### Update comment by id
PUT http://localhost:3000/comments/<comment-id>
Content-Type: application/json

{
  "content": "Updated comment text."
}

### Delete comment by id
DELETE http://localhost:3000/comments/<comment-id>
